# Build settings
permalink: /projects/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: false

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: ThatXRGuy
description: "I build things with code"
keywords: "thatxrguy, xrguy, xr, nem, developer, code, software, apps, application, web, mobile, dev, thatchocolateguy, github"
url: https://thatxrguy.com/
baseurl: ""

#google_analytics: UA-52446115-1
repo: http://github.com/ThatChocolateGuy
#disqus_shortname: "thatchocolateguy"
#disqus_site_shortname: "thatchocolateguy"

# Author settings
author:
  name: Nem Ekpunobi
  job: Moderately Stacked Developer
  bio: "Spatial computing enthusiast, interaction design and usability, always looking for the best project and good bubble tea."
  thumb: /images/author.jpg
  email: nemx14@gmail.com
  url: https://thatxrguy.com/
  github: https://github.com/ThatChocolateGuy
  twitter: https://twitter.com/thatchocobro
  instagram: https://instagram.com/thatchocolateguy
  facebook: https://facebook.com/thatchocolateguy
  linkedin: https://linkedin.com/in/grow-with-nem

# navbar pages
navbar:
#  - slug: about
#    title: About
#  - slug: icons
#    title: Icons
  - slug: projects
    title: Projects

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
