version: 1.3
encoding: utf-8

# Build settings
permalink: /projects/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [ jekyll-paginate-v2 ]

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 2
  permalink: "/page/:num/"
  sort_field: "date"
  sort_reverse: true

comments: false

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: nem.codes
description: "Emotion, engineered. | Building digital experiences that resonate. [A portfolio of Nem Ekpunobi - a full stack engineer with a passion for spatial computing and interaction design.]"
keywords: "thatxrguy, xrguy, nem.codes, xr, vr, ar, mixed reality, virtual reality, augmented reality, spatial computing, nem, nemo, developer, code, software, apps, application, web, mobile, dev, thatchocolateguy, github, full stack, full-stack, front-end, front end, developer, development, web developer, web development, full stack developer, full-stack developer, full stack engineer, full-stack engineer, full stack, software, engineer, software engineer, .NET, .NET developer, emotion, engineered, portfolio, nem ekpunobi, ekpunobi, nemx14"
url: https://nem.codes/
baseurl: ""

google_analytics: UA-135143182-1
repo: http://github.com/ThatChocolateGuy
#disqus_shortname: "thatchocolateguy"
#disqus_site_shortname: "thatchocolateguy"

# Author settings
author:
  name: Nem Ekpunobi
  nickname: Nemo
  job: Full Stack Engineer
  bio: "Spatial computing enthusiast, and interaction design buff; always looking for the best project and good bubble tea."
  thumb: /images/author.png
  email: nemx14@gmail.com
  url: https://nem.codes/
  github: https://github.com/ThatChocolateGuy
  twitter: https://twitter.com/thatchocobro
  instagram: https://instagram.com/thatchocolateguy
  facebook: https://facebook.com/thatchocolateguy
  linkedin: https://linkedin.com/in/grow-with-nem

# Project post settings
projects:
  ext-links:
    ct-demo: https://certitrack.nem.codes/

# story timeline content
story:
- title: An Immersive Experience
  year: 2017
  month: June
  blurb: After some self-reflection - driven by existential crisis - I decide to pivot from SaaS sales into the XR space (AR/VR/MR). I begin interning at a digital experience agency called <a href="https://metavrse.com/" target="_blank">MetaVRse</a>, where I work on a variety of mixed reality projects as an implementation specialist in the experiential marketing scene.
  img: /images/metavrse-vr-photobooth.jpeg
- title: A New Beginning
  month: December
  blurb: A few months into my internship experience, I realize I want to create experiences for the immersive future we're headed towards. This triggers my passion for software development, leading me to enroll in the Web & Mobile Development program at triOS College.
  img: /images/trios-classroom.jpg
- title: WordPress Wisdom
  year: 2018
  month: July
  blurb: Thanks to some encouragement from my instructor, I begin to take on projects for clients who need WordPress websites. The kickoff to my e-commerce expertise.<br/><a href="/wordpress" target="_blank" class="story-link-newline">Take a gander...</a>
  img: /images/wordpress-banner.jpg
- title: Machines can see
  month: September
  blurb: I begin to dabble in machine learning and computer vision, and start to see the potential of these technologies in the XR space. I begin to work on a few class projects that leverage these technologies, including <a href="/attendar" target="_blank">AttendAR</a>, a facial recognition app to track classroom attendance with ease.
  img: /images/facerecognition_1.jpg
- title: To be continued...

# navbar pages
navbar:
- slug: story
  title: Story
#  - slug: icons
#    title: Icons
- slug: projects
  title: Projects

exclude: [ "config.rb", "src", "Gemfile", "Gemfile.lock", "package.json", "README.md", "Rakefile" ]
